### ISSUE TITLE
有關打開shell的方法

### ISSUE THREAD

**Issue by typebrook** [wxnacy/wxnacy.github.io#1]
[Vim 执行 Shell 命令（2）](https://wxnacy.com/2019/04/18/vim-in-shell/) 中，應該還可以再多介紹 `:terminal`，分割視窗是很實用的操作

**Comment by wxnacy** [comment]
> [Vim 执行 Shell 命令（2）](https://wxnacy.com/2019/04/18/vim-in-shell/) 中，應該還可以再多介紹 `:terminal`，分割視窗是很實用的操作

谢谢您的提醒，用了一段时间发现很好用，今天做了补充，[Vim 执行 Shell 命令（3）](https://wxnacy.com/2019/05/17/vim-open-terminal/) 感谢您的关注
